# Generated by Django 2.1.3 on 2018-11-25 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=250, verbose_name='sender')),
                ('number', models.CharField(max_length=250, verbose_name='number')),
                ('message_id', models.TextField(blank=True, verbose_name='sender')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated on')),
            ],
        ),
    ]
