# Generated by Django 2.1.3 on 2018-11-29 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='response',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='response'),
            preserve_default=False,
        ),
    ]
