# Generated by Django 2.1.3 on 2018-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smslog_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=20, verbose_name='status'),
        ),
    ]
