
# Global variables for SMS system
DEFAULT_SMS_SENDER = "ProxiRental"
SMS_STATUS_SUBMITTED = "SUBMITTED"
SMS_STATUS_APPROVED = "APPROVED"
SMS_STATUS_DELIVERED = "DELIVERED"
SMS_STATUS_CANCELLED = "CANCELLED"
SMS_STATUS_INVALID_SMS = "INVALID_SMS"
