# Generated by Django 2.1.3 on 2019-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190101_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
