# Generated by Django 2.1.3 on 2018-12-02 10:36

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181201_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
