# Generated by Django 2.1.3 on 2018-12-19 19:39

from django.db import migrations, models
import main.defaults


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181202_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=50, verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=main.defaults.get_default_username, max_length=128, unique=True, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
