# Generated by Django 2.1.3 on 2018-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181219_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='verified_email'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='verified phone number'),
        ),
    ]
