# Generated by Django 2.1.3 on 2018-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181220_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='password_reset_code'),
        ),
    ]
